### ISSUE TITLE
Augment Modularized Code with Support for Cuda

### ISSUE THREAD

**Issue by kevin-seeger** [xevaballx/wildlife#15]
Adding some functionalities into the modularized code to support running on a machine with an Nvidia GPU.

**Comment by xevaballx** [comment]
The current code base is implemented to run on GPU. I’m hoping you can simply change your device in the config yaml. Let me know if it’s more complicated than that or if you have any questions.

**Comment by kevin-seeger** [comment]
I think that the only things I had to change to get everything running was a switch for pinning the dataloaders. I'll create PR and the changes can be reviewed.

**Comment by kevin-seeger** [comment]
Closing this out - no longer relevant.
