### ISSUE TITLE
Preprocesses based on day or night

### ISSUE THREAD

**Issue by kevin-seeger** [xevaballx/wildlife#16]
I wanted to take a look at clustering images in an unsupervised manner into (ideally) images taken during the day and those taken during the night. This is going to be somewhat exploratory and would need to be piped into an ensembled classifying system for this to be of any use.

**Comment by kevin-seeger** [comment]
Well, we're splitting data after nearly exploding my machine on the kmeans clustering fitting, but it looks like the images have sort of split on night/overexposed and not overexposed categories rather than "day/night". This could still be helpful, there might be some transforms that can help recover from the overexposure seen in the one cluster. 

Cluster0:
![image](https://github.com/user-attachments/assets/9095e838-5ca8-419d-adfb-a1c319c1974d)


Cluster1:
![image](https://github.com/user-attachments/assets/c5a10c51-fde4-4820-827e-a6bc143904b8)

**Comment by xevaballx** [comment]
I am curious how you would use this. Its interesting!

**Comment by kevin-seeger** [comment]
This would have to be feed into an ensembled classifier or we could use different transforms on the overexposed/bright images to maybe recover some information. Not sure if we'll get any boost in performance, though

**Comment by kevin-seeger** [comment]
I do wonder if feeding this into an ensembled classifier would increase performance. It looks like the clusters roughly correspond to over exposed and not over exposed, but we could increase the cluster count to at least 4 - one for the blue-ish images, one for color images, one for over exposed images, and one for night-time images. But this would take some time, and closing this out as it's not relevant anymore.
